AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "test/test_helper.rb"
    - "spec/mailers/previews/**/*"
    - "node_modules/**/*"
    - ".git/**/*"
    - "lib/tasks/**/*"
    - !ruby/regexp /old_and_unused\.rb$/
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

# Checks if there is a magic comment to enforce string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
